### ISSUE TITLE
Public ECR

### ISSUE THREAD

**Issue by RickyCook** [aws-actions/amazon-ecr-login#116]
When giving a public ECR like this (to push an image):
```
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: public.ecr.aws/deadbeef
```

The step fails and gives the error:
```
Member must satisfy regular expression pattern: [0-9]{12}
```
