### ISSUE TITLE
EKS IRSA Support? `Error saving credentials: error storing credentials - err: exit status 1, out: not implemented`

### ISSUE THREAD

**Issue by callum-tait-pbx** [aws-actions/amazon-ecr-login#147]
Using this on a EKS setup where IRSA is used to provide IAM access on our pods (our runners), when trying to chain `amazon-ecr-login` together with `configure-aws-credentials` I get the error below:

I can confirm IRSA is working fine as we have other pipelines using it fine, our runners are able to assume roles successfully and use the permissions in those assumed roles.

IRSA uses token files for authentication setting the `AWS_WEB_IDENTITY_TOKEN_FILE` env pointed at the token on disk.

**Output From Actions Log**
```shell
Run aws-actions/configure-aws-credentials@v1
  with:
    role-to-assume: arn:aws:iam::$MY_ACCOUNT_ID:role/$MY_ROLE
    aws-region: $MY_REGION
    role-duration-seconds: 900
1s
Run aws-actions/amazon-ecr-login@v1
  with:
  env:
    AWS_DEFAULT_REGION: $MY_REGION
    AWS_REGION: $MY_REGION
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
Error: Could not login: WARNING! Using -*** the CLI is insecure. Use --password-stdin.
Error saving credentials: error storing credentials - err: exit status 1, out: `not implemented`
```

**Workflow Yaml**
```yaml
- name: Configure AWS credentials
  uses: aws-actions/configure-aws-credentials@v1
  with:
    role-to-assume: arn:aws:iam::$MY_ACCOUNT_ID:role/$MY_ROLE
    aws-region: $MY_REGION
    role-duration-seconds: 900
- name: Login to ECR
  id: login-ecr
  uses: aws-actions/amazon-ecr-login@v1
```
