### ISSUE TITLE
 unable to push image to ECR

### ISSUE THREAD

**Issue by samuelarogbonlo** [aws-actions/amazon-ecr-login#166]
The pipeline part for this process is shown this 

```
name: Configure AWS credentials
              
          uses: aws-actions/configure-aws-credentials@v1
              
           with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

                aws-region: us-east-2

            - name: Login to Amazon ECR
            
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

           - name: Build, tag, and push image to Amazon ECR
           
              id: build-image

              env:

                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}

                ECR_REPOSITORY: service-t
```

The error is shown thus: 

```
name unknown: The repository with name 'service-t' does not exist in the registry with id '***'

Error: Process completed with exit code 1.
````

I have tried all means to solve this by confirming all correct parameters and repo is correct but still same error, I need help, how do I handle this please?
