### ISSUE TITLE
Support AssumeRoleWithWebIdentity

### ISSUE THREAD

**Issue by davidkarlsen** [aws-actions/amazon-ecr-login#206]
See: https://awsteele.com/blog/2021/09/15/aws-federation-comes-to-github-actions.html
It would be great if this action could configure the login, based on the presence of a an input parameter `AWS_ROLE_ARN`, calling the github api to obtain the token.

**Comment by davidkarlsen** [comment]
I tried a config like this:
```
  - name: Get OIDC token
      uses: zarnovican/aws-oidc-login-action@v1
      with:
        role: arn:aws:iam::xxxxxxxxx:role/somerole
        aws-region: eu-north-1
    - name: Login to ECR
      id: login-ecr
```

but it fails with:
```
Run aws-actions/amazon-ecr-login@v1.3.3
  with:
  env:
    AWS_WEB_IDENTITY_TOKEN_FILE: /tmp/awscred-1682-WR0Kr6NKctmg
    AWS_DEFAULT_REGION: eu-north-1
    AWS_REGION: eu-north-1
    AWS_ROLE_ARN: arn:aws:iam::xxxxxxxxx:role/somerole
Error: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
```

**Comment by abatilo** [comment]
@davidkarlsen, I actually have this working.

```yaml
name: Docker
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    concurrency: build-and-push
    permissions:
      id-token: write
      contents: read
    env:
      AWS_ROLE_ARN: arn:aws:iam::123412341234:role/ecr_pusher
      AWS_WEB_IDENTITY_TOKEN_FILE: /tmp/awscreds
      AWS_DEFAULT_REGION: us-east-1
      AWS_REGION: us-east-1
    steps:
      - uses: actions/checkout@v2

      - name: Use buildx
        uses: docker/setup-buildx-action@v1

      - name: assume role
        run: |
          sleep 5 # Race condition for runner to get ID token info injected
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sigstore" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/whi:${{ github.sha }}
          file: ./Dockerfile
          context: .
```

This works perfectly for me.
