### ISSUE TITLE
Download Action: Operation Canceled

### ISSUE THREAD

**Issue by raul-verdi** [aws-actions/amazon-ecr-login#236]
Good morning, this might not be entirely related to the code base of amazon-ecr-login, if there is a better place to report this, please advise.

I am using the ecr-login action as described in the docs:
```
- name: Configure AWS credentials
   uses: aws-actions/configure-aws-credentials@v1
   with:
     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     aws-region: ap-northeast-1

- name: Login to Amazon ECR
   id: login-ecr
   uses: aws-actions/amazon-ecr-login@v1
```
When running the action, the initial job, which is `setup`, fails to download the tarballs from the official actions, and the execution of the workflow gets cancelled.
Here is a screenshot of the issue

<img width="1387" alt="Screen Shot 2021-12-27 at 10 12 38" src="https://user-images.githubusercontent.com/95469166/147424851-a2e76355-2d8f-46da-8f45-358c1be15867.png">

**Comment by Abdullah-Shahen** [comment]
The combination of both actions, you are using, did not work for me. Therefore, I did it like:
````
      - name: Login to AWS Account
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Login to AWS ECR
        id: login-to-shared-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: private
````

I hope this helps.
