### ISSUE TITLE
Single registry entry fails

### ISSUE THREAD

**Issue by rbellamy** [aws-actions/amazon-ecr-login#27]
When working with a single `registryId`:

```yml
- name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: 012346789012
```

I get `Invalid parameter at 'registryIds' failed to satisfy constraint: 'Member must satisfy constraint: [Member must satisfy regular expression pattern: [0-9]{12}]'`. Yes, the `registryId` is twelve numeric digits.

When I remove the entry and rely on the default registry, it works.
