### ISSUE TITLE
Usage question with actions `services` and assume role

### ISSUE THREAD

**Issue by LyleDavis** [aws-actions/amazon-ecr-login#323]
Is there any recommended usage for GH Actions `services` key when using this action to retrieve ecr login details? They run before any steps in the job are performed so there's no way to run ecr-login beforehand.

My first thought was to login in one job and then use that in another job, like so:

```yaml
jobs:
  ecr-login:
    runs-on: ubuntu-latest
    outputs:
      docker_user: ${{ steps.login-to-ecr.outputs.docker_username_my_account_id_dkr_ecr_eu_west_1_amazonaws_com }}
      docker_password: ${{ steps.login-to-ecr.outputs.docker_password_my_account_id_dkr_ecr_eu_west_1_amazonaws_com }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: 'arn:aws:iam::my_account_id:role/my_role'
          role-duration-seconds: '3600'
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1
        id: login-to-ecr
  test:
    runs-on: ubuntu-latest
    needs: ecr-login
    services:
      param_store:
        image: my_account_id.dkr.ecr.eu-west-1.amazonaws.com/***/***
        credentials:
          username: ${{ needs.ecr-login.outputs.docker_user }}
          password: ${{ needs.ecr-login.outputs.docker_password }}
    
    ...
```

But this doesn't work because:
a) the post ecr-login step logs out of the repository
and
b) the docker_password is never output from the job because it's considered secret.

Are there any recommendations on how to handle this for github actions `services` node? account IDs and names of repos obscured for obvious reasons.
