### ISSUE TITLE
How to use ecr login with gh action services

### ISSUE THREAD

**Issue by 20vitality12** [aws-actions/amazon-ecr-login#331]
Hi! 
I have issue with ecr login when using postgres service.
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/40120520/183311770-a3f77732-9aa0-4880-ba7b-18ee2b2e78b1.png">

workflow code is: 
```
jobs:
  build-test:
    runs-on: ubuntu-latest
    container: node:14
    services:
      postgres:
        image: postgres:10.2
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    outputs:
      JOB_STATUS: ${{ steps.deployment.outputs.status }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
```
Please, help me with this error. A bit urgent for me.

**Comment by arjraman** [comment]
Hey @20vitality12, this is just a quick diagnosis, so it could be a different issue. But from testing your code myself, I think it's because Docker isn't installed in the container. The aws-actions/amazon-ecr-login action uses `docker login` to login the user to their ECR registry, which is where you most likely got your error.

To test this, I ran this job:
```
jobs:
  build-test:
    runs-on: ubuntu-latest
    container: node:14
    services:
      postgres:
        image: postgres:10.2
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    outputs:
      JOB_STATUS: ${{ steps.deployment.outputs.status }}
    steps:
      - name: Test docker
        run: docker
```
and got the following error:
<img width="994" alt="Screen Shot 2022-08-07 at 4 08 32 PM" src="https://user-images.githubusercontent.com/65422301/183314609-c2d142d8-09d9-4dc8-a906-8ec3f05f0b16.png">

As you can see, Docker wasn't found. See if you can run commands to install it in a previous step using the link [here](https://docs.docker.com/engine/install/).

**Comment by 20vitality12** [comment]
@arjraman thx you! I have resolved this issue with removing `container: node:14`  ant setup postgres ports to 5432/tcp and access db with locahost
```
jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.2
        ports:
          - 5432/tcp
    steps:
      ...
      - name: Prisma generate && migrate deploy
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres?schema=public
        run: npx nx generate:client prisma && npx nx migrate:deploy prisma              
```
`${{ job.services.postgres.ports[5432] }}` also important to use this command
