### ISSUE TITLE
Authentication error when pushing to different account in same region

### ISSUE THREAD

**Issue by dmkim22-lguplus** [aws-actions/amazon-ecr-login#334]
Hello,

I need to push an image to account A ECR, using account B's IAM user, but when I use `aws-actions/amazon-ecr-login@v1`, I receive "no basic auth credentials" error. Account A and B are in same region.
But if I switch to `aws ecr get-login-password` & `docker login` method for ECR login, image is pushed to account A ECR with no problem..

So this workflow ends with "no basic auth credentials" error : 
```
    - name: Configure AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: <Account B Access Key>
          aws-secret-access-key: <Account B Secret Access Key>
          aws-region: <A&B Region>

      - name: AWS ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Docker Build & Push to ECR
        run: |
          docker build -t <Account A ECR Repository>:<tag> -f Dockerfile .
          docker push <Account A ECR Repository>:<tag>
```

But for `aws ecr get-login-password` & `docker login`, push succeeds.
```
    - name: Configure AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: <Account B Access Key>
          aws-secret-access-key: <Account B Secret Access Key>
          aws-region: <A&B Region>

      - name: AWS ECR Login
        run: |
          aws ecr get-login-password --region <A&B Region> | docker login --username AWS --password-stdin <Account A ECR Registry>

      - name: Docker Build & Push to ECR
        run: |
          docker build -t <Account A ECR Repository>:<tag> -f Dockerfile .
          docker push <Account A ECR Repository>:<tag>
```

Is there anything that I need to do differently for this kind of job?

Here is my ECR Permission on account A just for reference.. But I'm guessing the permission setting is the issue here as `aws ecr get-login-password` & `docker login` with same `aws-actions/configure-aws-credentials` works.

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "arn:aws:iam::<Account B ID>:root"
        ]
      },
      "Action": [
        "ecr:BatchCheckLayerAvailability",
        "ecr:BatchGetImage",
        "ecr:CompleteLayerUpload",
        "ecr:DescribeImages",
        "ecr:GetDownloadUrlForLayer",
        "ecr:InitiateLayerUpload",
        "ecr:PutImage",
        "ecr:UploadLayerPart"
      ]
    }
  ]
}
```

Thank you.

**Comment by arjraman** [comment]
So to push to region A, you have to first login to region A. You can specify that in the action with the 'registry' input. You can read more about it in the action.yml file.

**Comment by dmkim22-lguplus** [comment]
@arjraman Thank you for your feedback.

Accounts A & B are both in the same region.
However, I did check out the action.yml file and tested with "registries" option as you suggested, and it worked! 

Thank you.

```
    - name: Configure AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: <Account B Access Key>
          aws-secret-access-key: <Account B Secret Access Key>
          aws-region: <A&B Same>

      - name: AWS ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: <Account A ID>
```
