### ISSUE TITLE
pick up on AWS_DEFAULT_REGION environment variable

### ISSUE THREAD

**Issue by pdeveltere** [aws-actions/amazon-ecr-login#367]
AWS_DEFAULT_REGION is an official environment variable in AWS https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html#envvars-list.

In my workflow I specify:
```
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-central-1
```

which is needed for some other jobs. It would be nice if we do not have to set the region again with:
```
with:
   aws-region: $AWS_DEFAULT_REGION
```

but that it can pick this up automatically 🙏🏽
