### ISSUE TITLE
Docker push always retrying

### ISSUE THREAD

**Issue by ibrajer-embed** [aws-actions/amazon-ecr-login#386]
Hi, I'm trying to use Github Actions and AWS ECR with OpenID Connect (OIDC) and I followed these instructions: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#configuring-the-role-and-trust-policy

I have created a new role in IAM with the following permission policy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "ecr:BatchGetImage",
                "ecr:BatchCheckLayerAvailability",
                "ecr:CompleteLayerUpload",
                "ecr:GetDownloadUrlForLayer",
                "ecr:InitiateLayerUpload",
                "ecr:PutImage",
                "ecr:UploadLayerPart"
            ],
            "Resource": "arn:aws:ecr:eu-central-1:xxxxxxxxxxxxxx:repository/xxxxxxxxxxxxxx.dkr.ecr.eu-central-1.amazonaws.com/my-repository"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "ecr:GetAuthorizationToken"
            ],
            "Resource": "*"
        }
    ]
}
```

And trusted entities:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::yyyyyyyyyyyy:oidc-provider/token.actions.githubusercontent.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringLike": {
                    "token.actions.githubusercontent.com:sub": "repo:my-org/my-repository:*"
                },
                "StringEquals": {
                    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
                }
            }
        }
    ]
}
```

And this is my workflow file:

```
name: Upload Docker image to AWS ECR

on:
  push:
    branches:
      - github-actions

permissions:
  id-token: write
  contents: read

jobs:
  upload_image:
    name: Tag and upload Docker image to AWS ECR
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::zzzzzzzzzzzzzz:role/github-actions-role
          role-session-name: temp-session

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1.5.3

      - name: Build, tag, and push Docker image to AWS ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: my-repository
          IMAGE_TAG: ${{ github.ref_name }}-${{ github.sha }}
        run: |
          docker build --target=release -t $REPOSITORY .
          docker tag $REPOSITORY $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
```

I have tried so many things already and simply can't get it working... The output is always the following:

```
Successfully built ee48563b6bb3
Successfully tagged my-repository:latest
The push refers to repository [***.dkr.ecr.eu-central-1.amazonaws.com/my-repository]
61a354868119: Preparing
888029d0e424: Preparing
a46f7ee10905: Preparing
9b77b076837c: Preparing
c43e4ddc5992: Preparing
e5896e4ce6c3: Preparing
7c40600bc52d: Preparing
d326469892d9: Preparing
b5ebffba54d3: Preparing
e5896e4ce6c3: Waiting
7c40600bc52d: Waiting
d326469892d9: Waiting
b5ebffba54d3: Waiting
a46f7ee10905: Retrying in 5 seconds
9b77b076837c: Retrying in 5 seconds
888029d0e424: Retrying in 5 seconds
61a354868119: Retrying in 5 seconds
// ... retrying repeats a lot ... //
a46f7ee10905: Retrying in 5 seconds
9b77b076837c: Retrying in 5 seconds
Error: The operation was canceled.
```

Can you please help? Is there something here that I'm missing or doing wrong? Thank in advance!
