### ISSUE TITLE
unable to push image to ECR

### ISSUE THREAD

**Issue by KlimDos** [aws-actions/amazon-ecr-login#4]
permissions for the user who running pipeline - 
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "ecr:*",
            "Resource": "*"
        }
    ]
}
```
pipeline step Login to Amazon ECR succeeds
```yaml

    AWS_REGION: us-east-1
Run aws-actions/amazon-ecr-login@v1
  with:
  env:
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_DEFAULT_REGION: us-east-1
    AWS_REGION: us-east-1
```
registry - `475882391631.dkr.ecr.us-east-1.amazonaws.com/contenttech`

error:
```bash
name unknown: The repository with name '***.dkr.ecr.us-east-1.amazonaws.com/contenttech' does not exist in the registry with id '***'
##[error]Process completed with exit code 1.
```
details and full pipeline - 
[link](https://github.com/KlimDos/telegram-send-docker/commit/caa2ad2b5d1f7533ffa0701ccabd92bc18641215/checks?check_suite_id=325635263)

**Comment by KlimDos** [comment]
I did understand wrong what to put in ECR_REPOSITORY
instead of URL I should use just repository name 
```yaml
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: contenttech/telegram-send-docker
```
instead of 
```yaml
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: 475882391631.dkr.ecr.us-east-1.amazonaws.com/contenttech/telegram-send-docker
````

**Comment by samuelarogbonlo** [comment]
@KlimDos Would you mind helping? I have similar issue in my build but even after putting the ECR repo link, the build still fails with same error

**Comment by KlimDos** [comment]
@samuelarogbonlo Hey Samuel 
Not sure if I am able to help since I was doing this more than two years ago, but lets have a look 
 - first share your pipline (link to the repo or paste code here (make sure there is no sensitive data within))
 - are you sure your Github action successfully authorized into AWS (you can try to perform some simple operation using env vars you set in the github config)
 
 ```
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
 ```
 
for instance gain some extra perms to this KEY and try to list s3 buckets
