### ISSUE TITLE
Allow transfer output from amazon-ecr-login step to step in different job

### ISSUE THREAD

**Issue by rafzei** [aws-actions/amazon-ecr-login#400]
Problem:
Currently, there is no way (at least an easy way) to get output from aws-actions/amazon-ecr-login job in another job.
Like in [integ-tests](https://github.com/aws-actions/amazon-ecr-login/blob/integ-tests/.github/workflows/test-workflow.yml) currently is possible to get output only from a `step` and within one job.

If I declare output from a job:
```
jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

    outputs:
      registry: ${{ steps.login-ecr.outputs.registry }}
```
I get `Warining: Skip output 'registry' since it may contain secret.`

By default, the gh action masks the registry as follows: `***.dkr.ecr.***.amazonaws.com`

Proposed solution:
If possible, add a new input to `aws-actions/amazon-ecr-login` to not mask the registry output.
```
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with: 
          mask-registry: no
```
