### ISSUE TITLE
no basic auth credentials error for random builds 

### ISSUE THREAD

**Issue by davi020** [aws-actions/amazon-ecr-login#431]
Some time when pipeline fails with the below error:
no basic auth credentials,
it does not happens regularly but in every 10-15 days this issue is occurring.

```
Pipeline steps:

  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v1
    with:
     aws-region: ${{env.REGION}}
     role-to-assume: ${{env.ASSUME_ROLE}}
     role-duration-seconds: 1200
     role-skip-session-tagging: true
          

  - name: Login to Amazon ECR 
    id: login-ecr
    uses: aws-actions/amazon-ecr-login@v1
    
  - name: Build, tag, and push image to Amazon ECR
    env:          
      ECR_URL: ${{ steps.login-ecr.outputs.registry }}
    run: |
      docker build -t $ECR_URL/$ECR_REPO:$IMAGE_TAG .
      docker push $ECR_URL/$ECR_REPO:$IMAGE_TAG
```

My setup -

* Have 3 runner instances in my self-hosted github runner
* Using assume role to authenticate with AWS
* If a build fails, the next build will pass. Issue occurring on random builds 

Logs 
`Successfully built 96a7fcd1b011
Successfully tagged ***.dkr.ecr.eu-central-1.amazonaws.com/registry:latest
The push refers to repository [***.dkr.ecr.eu-central-1.amazonaws.com/registry]
374b29f6eb29: Preparing
02541b6f86e9: Preparing
d36dc390a6a2: Preparing
28adcc2eea7f: Preparing
8c667e7e65fe: Preparing
no basic auth credentials
Error: Process completed with exit code 1.`
