### ISSUE TITLE
ECR username and password not available in later step in same job

### ISSUE THREAD

**Issue by WTPascoe** [aws-actions/amazon-ecr-login#440]
**Describe the bug**
I'm attempting to use the `docker_username` and `docker_password` in a later step. These values do not seem to be populated.

**To Reproduce**
```
jobs:
  docker:
    name: Build the docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                role-to-assume: arn:aws:iam::myaccount:role/myrole
      - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1
      - name: Build image with Kaniko
        env:
          USERNAME: ${{ steps.login-ecr.outputs.docker_username_myaccount_dkr_ecr_eu_west_1_amazonaws_com }}
          PASSWORD: ${{ steps.login_ecr.outputs.docker_password_myaccount_dkr_ecr_eu_west_1_amazonaws_com }}
        run: |
          AUTH_STRING=$(echo -n "${USERNAME}:${PASSWORD}" | base64)
          echo "AUTH STRING: $AUTH_STRING"
```

This produces the following output in GitHub
```
Run AUTH_STRING=$(echo -n "${USERNAME}:${PASSWORD}" | base64)
Username: 
Password: 
AUTH STRING: Og==
```

**Expected behavior**
I would expect AUTH_STRING to be a longer string where the current value is simply the base64 encoded value of ":"

**Additional context**
I've looked at https://github.com/aws-actions/amazon-ecr-login/issues/308 which seems similar, but this was resolved.
