### ISSUE TITLE
Error: getaddrinfo ENOTFOUND api.ecr-public.ap-northeast-1.amazonaws.com

### ISSUE THREAD

**Issue by allisweb3** [aws-actions/amazon-ecr-login#537]
**Describe the bug**
github action not working with error:  "Error: getaddrinfo ENOTFOUND api.ecr-public.ap-northeast-1.amazonaws.com"

```
Run aws-actions/amazon-ecr-login@v2
  with:
    registry-type: public
    mask-password: true
    skip-logout: false
  env:
    AWS_DEFAULT_REGION: ap-northeast-1
    AWS_REGION: ap-northeast-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
Error: getaddrinfo ENOTFOUND api.ecr-public.ap-northeast-1.amazonaws.com
```

```
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public
```

**Expected behavior**
build and push image to ECR public

**Screenshots**
![shot](https://i.ibb.co/74491VK/i-Shot-2023-10-08-12-54-40.png)

**Desktop (please complete the following information):**
 - OS: [e.g. ubuntu-latest]
