### ISSUE TITLE
Building image and then reusing it fails

### ISSUE THREAD

**Issue by KostLinux** [aws-actions/amazon-ecr-login#551]
**Describe the bug**
I have Action that builds and pushes image to ECR, after that i want to use that image, but even trying with environmental variables, github contexts and so on - at the verification step it still fails with -> Error: The template is not valid. .github/workflows/verify_build_deploy.yml (Line: 87, Col: 19): Unexpected value '',.github/workflows/verify_build_deploy.yml (Line: 88, Col: 19): Unexpected value ''
Or Docker login for '' failed with exit code 1

**To Reproduce**
1. Create ECR Private Registry with AWS Secrets and Access Keys
2. Copy paste this action
3. Run it

**Expected behavior**
Successfully pulls container from ECR and runs hello world

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. ubuntu-latest]
 - Version [e.g. 1.5.0]

**Additional context**
Actions:

Github action looks like that
```
  get_data:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    # https://github.com/aws-actions/amazon-ecr-login#docker-credentials
    outputs:
      docker-registry: ${{ steps.login-ecr.outputs.registry }}
      docker-username: ${{ steps.login-ecr.outputs.docker_username_MY_ACCOUNT_ID_dkr_ecr_AWS_REGION_amazonaws_com }}
      docker-password: ${{ steps.login-ecr.outputs.docker_password_MY_ACCOUNT_ID_dkr_ecr_AWS_REGION_amazonaws_com }}
      image-tag: ${{ steps.create_tag.outputs.tag }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets[format('{0}_AWS_ACCESS_KEY_ID', github.ref_name)] }}
          aws-secret-access-key: ${{ secrets[format('{0}_AWS_ACCESS_KEY_SECRET', github.ref_name)] }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create tag
        id: create_tag
        run: echo "tag=$(echo ${{ github.ref_name }} | cut -c -4)-$(echo ${{ github.sha }} | cut -c -8)" >> "$GITHUB_OUTPUT"

  build_image:
    runs-on: ubuntu-latest
    needs: get_data
    env:
      ECR_REGISTRY: ${{ needs.get_data.outputs.docker-registry  }}
      ECR_REPOSITORY: my_sample_app
      IMAGE_TAG: ${{ needs.get_data.outputs.image-tag }}
      TAG: ${{ needs.get_data.outputs.image-tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build  --file dockerfile --tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ needs.get_data.outputs.docker-registry }}
          username: ${{ secrets[format('{0}_AWS_ACCESS_KEY_ID', github.ref_name)] }}
          password: ${{ secrets[format('{0}_AWS_ACCESS_KEY_SECRET', github.ref_name)] }}

      - name: Deploy image
        run: docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  verification:
    needs:
      - get_data
      - build_image
    container:
      image: ${{ needs.get_data.outputs.docker-registry }}/my_sample_app:${{ needs.get_data.outputs.image-tag }}
      credentials:
        username: ${{ needs.get_data.outputs.docker-username }}
        password: ${{ needs.get_data.outputs.docker-password }}
    runs-on: ubuntu-latest
    steps:
      - name: "Hello world"
        run: echo "Hello world"
        
```

**Comment by KostLinux** [comment]
Also it skips output - Warning: Skip output 'docker-password' since it may contain secret.

**Comment by KostLinux** [comment]
Adding mask-password: 'false' fixed the problem....
```
     - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'false'
          ```
