### ISSUE TITLE
Docker Login fails with V2; Move from --password to --password-stdin

### ISSUE THREAD

**Issue by PranY** [aws-actions/amazon-ecr-login#574]
**Bug Description**
When I run the V2 login on ubuntu-latest, it works fine but when I run it with a self-hosted runner (running on EC2 in the same AWS account as ECR), the docker login throws an error message.

Error: Could not login to registry ***: WARNING! Using --password via the CLI is insecure. Use --password-stdin.

**Problem Root**
index.js <line 161>

**To Reproduce**
```yaml
  name: Test Pipeline
  
  on:
    push:
  
  permissions:
    id-token: write
    contents: read
  
  jobs:
    integration:
      name: Continuous Integration
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3
  
        - name: Lint code
          run: echo "Linting repository"
  
        - name: Run unit tests
          run: echo "Running unit tests"
  
    build-and-push-ecr-image:
      name: Push to ECR
      needs: integration
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3
  
        - name: Install Utilities
          run: |
            sudo apt-get update
            sudo apt-get install -y jq unzip
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
  
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2
  
        - name: Build, tag, and push image to Amazon ECR
          id: build-image
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
            IMAGE_TAG: latest
          run: |
            # Build a docker container and
            # push it to ECR so that it can
            # be deployed to ECS.
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
    
    Continuous-Deployment:
      runs-on: self-hosted
      needs: build-and-push-ecr-image
      steps:
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
  
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2
        
        - name: Pull latest images
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
            IMAGE_TAG: latest
          run: |
            docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
        - name: Delete Previous Container
          run: |
            docker rm -f creditcard || true
  
        - name: Run Docker Image to serve users
          run: |
            docker run -d -p 8080:8080 --name=creditcard -e 'AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}' -e 'AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}' -e 'AWS_REGION=${{ secrets.AWS_REGION }}'  ${{secrets.AWS_ECR_LOGIN_URI}}/${{ secrets.ECR_REPOSITORY_NAME }}:latest
```

**Expected behaviour**
V2 login should work on both ubuntu-latest and self-hosted runners. In the below screenshot, Push to ECR steps uses the same login and it works fine but the Continuous Deployment stage fails with the exact same code on a self-hosted runner.

**Screenshots**
<img width="1210" alt="image" src="https://github.com/aws-actions/amazon-ecr-login/assets/767894/56cfb8ab-34c6-49bc-8836-29c0eb89022c">

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11

**Additional context**
