### ISSUE TITLE
[Feature request] Remove dependency on docker client

### ISSUE THREAD

**Issue by runlevel5** [aws-actions/amazon-ecr-login#598]
From my understand to perform authentication, the action utilises the `docker` client to perform `docker login`. Which is fine. However this dependency will make this plugin incompatible with environment that does not ship docker client (or users could not install any software). IMHO the action should take advantage of the HTTP API endpoint to perform this task instead.

**Comment by szhekpisov** [comment]
Same here, have a version v2.

**Comment by runlevel5** [comment]
I am more than happy to offer a Pull Request if the team approves this proposal

**Comment by gricey432** [comment]
I think this would also solve #434 ?

**Comment by runlevel5** [comment]
> I think this would also solve https://github.com/aws-actions/amazon-ecr-login/issues/434 ?

Yes it would

**Comment by mohitgarg** [comment]
@runlevel5 is there a workaround for this? I tried using another runner but then `node` would fail in $PATH.

**Comment by runlevel5** [comment]
> @runlevel5 is there a workaround for this? I tried using another runner but then node would fail in $PATH.

AFAIK the answer is _no_.

**Comment by marcindruzgala** [comment]
The issue is that HTTP API is rate limited, and the limit of http calls is very low per day - I had this issue when requesting auth token from ECR using Pulumi

**Comment by runlevel5** [comment]
> The issue is that HTTP API is rate limited, and the limit of http calls is very low per day - I had this issue when requesting auth token from ECR using Pulumi

It is true but how is it different to the mechanism of `docker login`?

**Comment by marcindruzgala** [comment]
> It is true but how is it different to the mechanism of `docker login`?

That I don't have answer to - I only know that I can run hundreds of jobs every day using this GitHub Action and I'm not rate limited, when I was testing building docker using Pulumi and requesting ecr credentials using http calls I started getting rate limited after few tests 🤷‍♂

**Comment by l0rem1psum** [comment]
For anyone looking for a workaround:

Instead of:

```yaml
- name: Configure AWS
  uses: aws-actions/configure-aws-credentials@v4.1.0
  with:
    aws-region: us-east-1
    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

- name: Login to Amazon ECR Private
  uses: aws-actions/amazon-ecr-login@v2
```

Do:

```yaml
- name: Configure AWS
  uses: aws-actions/configure-aws-credentials@v4.1.0
  with:
    aws-region: us-east-1
    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

- name: Setup ECR Credential Helper
  run: |
    mkdir -p ~/.docker
    echo '{"credHelpers": {"${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com":"ecr-login"}}' > ~/.docker/config.json
```

Make sure to install [`amazon-ecr-credential-helper`](https://github.com/awslabs/amazon-ecr-credential-helper) before.

Solution verified with `buildah`
