### ISSUE TITLE
Action does not support EKS pod identities

### ISSUE THREAD

**Issue by casey-robertson-paypal** [aws-actions/amazon-ecr-login#624]
**Describe the bug**
We are migrating workloads to EKS - in particular Github Actions runners.  The runner scalesets run as service accounts wired up to AWS EKS Pod Identities.  We run v2 of the action and receive the following error:

```
Run aws-actions/amazon-ecr-login@v2
  with:
    mask-password: true
    registry-type: private
    skip-logout: false
Error: 169.254.170.23 is not a valid container metadata service hostname
```

**To Reproduce**

Create a test action that uses `amazon-ecr-login` in a pod/runner running in EKS and a service account identity.  

**Expected behavior**
The action discovers the creds mounted in the metadata path and uses them to authenticate with ECR.  

**Screenshots**
No screenshots but we confirmed that raw `aws sts` commands are returning the correct assumed role that we'd expect.

**Desktop (please complete the following information):**
 EKS 1.29
Running 0.9.0 version of github action runner container and helm chart.

**Comment by meithon** [comment]
Current Workaround
At present, one of the most effective solutions appears to be using the following action instead:


```
- name: Login to Amazon ECR
  id: login-ecr
  run: |
    aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin xxxxxxxxxxxx.dkr.ecr.ap-northeast-1.amazonaws.com
    aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin xxxxxxxxxxxx.dkr.ecr.ap-northeast-1.amazonaws.com
```

**Comment by zarko-a** [comment]
Another workaround that might be better if you are using kubernetes driver for buildx is to not use `aws-actions/amazon-ecr-login` and use https://github.com/docker/login-action instead. It supports Pod Identity out-of-the box and no extra steps are needed. Kinda disappointing that official AWS Actions are outdated compared to Docker. 

If you are using Pod Identity with EKS this is needed to get buildx with k8s pushing to private ECR. Maybe this saves someone time.

```
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@97834a484a5ab3c40fa9e2eb40fcf8041105a573 # pinned to a specific commit to enable pod identity support. None of the existing v4 tags support it yet.  See here for details https://github.com/aws-actions/configure-aws-credentials/issues/942
        with:
          aws-region: < region >
          
      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry:  <aws account id>.dkr.ecr.< region >.amazonaws.com

      - name: Generate Dynamic Tag
        id: tag
        run: echo "image-tag=$(date +'%Y-%m-%d-%H-%M')" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: kubernetes
          driver-opts: |
            namespace=docker-buildx
            "nodeselector=kubernetes.io/arch=amd64"
            "annotations=karpenter.sh/do-not-disrupt=true"
            "tolerations=key=node-role,value=static,effect=NoSchedule"

      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: ./scripts/test_image
          push: true
          provenance: false
          tags: <aws account id>.dkr.ecr.< region >.amazonaws.com/<repo name>:${{ steps.tag.outputs.image-tag }}
```
