### ISSUE TITLE
Output whether an ECR repository is immutable

### ISSUE THREAD

**Issue by pascalgulikers** [aws-actions/amazon-ecr-login#760]
**Is your feature request related to a problem? Please describe.**
When using an existing tag and/or latest, when building an image, it would be nice to know it that's possible before building

**Describe the solution you'd like**

For example:
```
- name: Login to Amazon ECR
  id: login-ecr
  uses: aws-actions/amazon-ecr-login@v2

- name: Extract Docker metadata
  id: meta
  uses: docker/metadata-action@v5
  with:
    images: ${{ inputs.image-path }}
    flavor: |
      latest=${{ fromJSON(steps.login-ecr.outputs.mutable) }} # Push latest tag if true, immutable has to be false
   tags: |
      type=raw,value=${{ inputs.image-version }}.${{ github.run_id }} # Push unique tag for each build
      type=raw,value=${{ inputs.image-version }},enable=${{ fromJSON(steps.login-ecr.outputs.mutable) }} # Also push base image version (immutable has to be false)

- name: Build Docker image
  id: build-image
  uses: docker/build-push-action@v6
         
```

**Describe alternatives you've considered**
Get the ECR repo properties with AWS CLI

**Additional context**
