### ISSUE TITLE
Action fails to parse 403 response from AWS ECR and displays empty error.

### ISSUE THREAD

**Issue by SmashingQuasar** [aws-actions/amazon-ecr-login#766]
**Describe the bug**

We have a pipeline using the [configure-aws-credentials](https://github.com/aws-actions/configure-aws-credentials) Github action. It uses an OIDC provider as recommended by AWS.
This aciton then assumes a role that uses the following IAM policy:

```json
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid": "ECRAnonymisedRepository",
			"Effect": "Allow",
			"Action": [
				"ecr:DescribeImages",
				"ecr:ListImages",
				"ecr:PutImage"
			],
			"Resource": [
			    "arn:aws:ecr:eu-west-3:039612883563:repository/anonymised-repository"
		    ]
		},
		{
			"Sid": "ECRAllResources",
			"Effect": "Allow",
			"Action": [
				"ecr:GetAuthorizationToken",
				"ecr:InitiateLayerUpload",
				"ecr:UploadLayerPart",
				"ecr:CompleteLayerUpload"
			],
			"Resource": "*"
		}
	]
}
```

**To Reproduce**

⚠ Requires a **valid** Docker image build, you also need to adapt the syntax to use your own scripts. Building a Docker image is out of the scope of this issue. ⚠ 

The following workflow fragment should reproduce the issue:

```yaml
  build:
    runs-on: ubuntu-latest
    environment: 'anonymised-environment'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          build.sh
          push.sh
```

**Expected behavior**

The workflow should output the error returned by AWS instead of a JSON parsing error.

**Screenshots**

Here is a screenshot of the output:

![Image](https://github.com/user-attachments/assets/aa6d6033-22a7-499b-93ac-c0d99aaef4a6)

**Desktop (please complete the following information):**
 - OS: [e.g. ubuntu-latest]
 - Version [e.g. 1.5.0]

**Additional context**

This is **very** likely tied to AWS inconsistently returning JSON or XML without real logic within its API.
Since XML is, at this point in time, an antiquated relic of a long-forgotten past, it is normal that the Node.js client fails to parse it as JSON. There should most likely be a fallback in the action to prevent a wrongful output.
